global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # EMC2-Core service
  - job_name: 'emc2-core'
    static_configs:
      - targets: ['host.docker.internal:3001']
    metrics_path: '/metrics'

  # OpenTelemetry Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  # Jaeger
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']

# Alerting rules (example)
rule_files:
  - 'alerts.yml'

# Alert manager configuration (if using)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
