services:
  postgres:
    image: postgres:15-alpine
    container_name: mortgage_broker_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-mortgage_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mortgage_pass}
      POSTGRES_DB: ${POSTGRES_DB:-mortgage_broker_pro}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-mortgage_user}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: mortgage_broker_pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

  emc2-core:
    build:
      context: ./services/emc2-core
      dockerfile: Dockerfile.dev
    container_name: mortgage_broker_emc2_core
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mortgage_broker_pro
      - DB_USER=mortgage_user
      - DB_PASSWORD=mortgage_pass
    env_file:
      - .env
      - .env.azure
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      # Mount source code only, not node_modules
      - ./services/emc2-core/src:/app/src
      - ./services/emc2-core/package.json:/app/package.json
      - ./services/emc2-core/package-lock.json:/app/package-lock.json
      - ./services/emc2-core/tsconfig.json:/app/tsconfig.json
      - ./services/emc2-core/nodemon.json:/app/nodemon.json
    command: npm run dev

  redis:
    image: redis:7-alpine
    container_name: mortgage_broker_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: mortgage_broker_postgres_data
  pgadmin_data:
    name: mortgage_broker_pgadmin_data

networks:
  default:
    name: mortgage_broker_network
